### ISSUE TITLE
Npm install

### ISSUE THREAD

**Issue by calr0x** [calr0x/OT-DockSucker#19]
To the dockerless gods who run the github, I have a request!

My dockerless node has always had errors running npm install that didn't seem to break anything but i've finally figured out what fixes them:
sudo apt-get install libpq-dev

may be worth seeing if this can go in the dockerless install script if it's not already?

**Comment by calr0x** [comment]
This library is for postgres databases which are not used.

**Comment by lukeskinner** [comment]
:(

**Comment by calr0x** [comment]
Gdammit.
